### ISSUE TITLE
lookup doesn't respect value "list" option when there is a single attribute

### ISSUE THREAD

**Issue by ghost** [quinot/ansible-plugin-lookup_ldap#15]
also the docs seem to need update as this option seem to be named "always_list".

**Comment by quinot** [comment]
Does it behave correctly when you set the option as "always_list"?

**Comment by ghost** [comment]
nope i tried that too, the problem seem to be on this [if clause](https://github.com/quinot/ansible-plugin-lookup_ldap/blob/master/lookup_plugins/ldap.py#L210) that doesn't check for the `always_list` option, maybe i'm misunderstanding the usage of this option.

**Comment by quinot** [comment]
OK, can you show what your configuration is, what result you are getting, and what result you'd expect?

**Comment by ghost** [comment]
I'm searching through LDAP Groups and filtering the `member` attributes of each group, 
some groups may have more than one member but they are always returned one by one as strings even if `always_list` is true. I will cleanup my ansible play to a minimal example and post it.

**Comment by quinot** [comment]
Thanks, that will be very helpful!

**Comment by quinot** [comment]
Still waiting for your input to analyze the issue...

**Comment by ghost** [comment]
okay, so my LDAP structure has 'Groups' and those groups have 'mailGroupMember' values, 

```
context:
      base: 'ou=Groups,dc=example,dc=com'
      filter: '(&(mailEnableIMAP=TRUE)(mailEnabled=TRUE))'
      value:
        - mailGroupMember:
            always_list: yes
```
Some groups have more than one 'mailGroupMember' 
I want a list of lists of the members of each Group but instead i get a single list of ALL group members, 
so the `always_list` in the case of one `value` effectively does nothing, having more than one `value` works as expected. 

does this makes sense? my previous link about the if clause was wrong, i was talking about [this](https://github.com/quinot/ansible-plugin-lookup_ldap/blob/master/lookup_plugins/ldap.py#L219), the `always_list` option is only getting honored when `single_attr` is `None` cause of [this](https://github.com/quinot/ansible-plugin-lookup_ldap/blob/master/lookup_plugins/ldap.py#L158) clause

**Comment by ghost** [comment]
any news on this? i tried to take it but i can't find a way to fix this without refactoring the whole plugin.

**Comment by quinot** [comment]
As I asked in January: "what result you are getting, and what result you'd expect?"

**Comment by ghost** [comment]
as i already answered in January, two comments above this: 
> I want a list of lists of the members of each Group but instead i get a single list of ALL group members,
so the always_list in the case of one value effectively does nothing, having more than one value works as expected.

if that wasn't clear enough i could not know and i've already asked if that makes sense.
i've even pointed out the part of the code where the bug is which is pretty obvious if you take a look at the lines. Not sure what more information i can provide to make this clearer.

**Comment by ghost** [comment]
Still need more explanation?

**Comment by ghost** [comment]
> what result you are getting

A list of all the group members

>  what result you'd expect

a list of lists of members of each group,

meaning i'm expecting `always_list` to work without having to add more values
to work around this, cause if there is a single value the [always_list](https://github.com/quinot/ansible-plugin-lookup_ldap/blob/master/lookup_plugins/ldap.py#L251) is not getting honored cause of this [beauty](https://github.com/quinot/ansible-plugin-lookup_ldap/blob/master/lookup_plugins/ldap.py#L219).
Lets recap, having only one value or a `single_attr` as it's called in the source the `always_list` option is not getting honored and the result is a flatten list instead of a list of lists. (yeah super inconsistent names between source and docs and LDAP itself)

Getting there?

You can always ask for more information if you still don't understand the otherwise obvious bug. but not responding is not a way to make the other person understand that they have not provided enough information.

**Comment by quinot** [comment]
Please also indicate how your playbook uses the LDAP lookup. Do you use a with_ldap loop? A call to the lookup() function in a template? Can you show the exact output you are observing (ie copy/paste it)?

**Comment by quinot** [comment]
I'm still not quite sure what exactly you are trying to achieve. On Jan 12 you said you'd send a stripped down version of your playbook. So do feel free to send it. It will be helpful.

**Comment by ghost** [comment]
> Do you use a with_ldap loop? A call to the lookup() function in a template?

ansible uses `lookup` in the `with_` loops so this is exactly the same thing, the consumer of the result is irrelevant, the result of the lookup is what matters, i expected more knowledge from a plugin developer

> Can you show the exact output you are observing (ie copy/paste it)?

you're asking for output that is irrelevant to the plugin functionality, cause after all this plugin doesn't have a single logging message.

---
I've already commented my playbook's context for the lookup but apparently is not enough to get the point across, i've added debug tasks so this is easier to understand your own plugin.

with single attribute:

playbook:
```yaml
---
- hosts: localhost
  vars:
    group_context:
      base: 'ou=Groups,dc=example,dc=com'
      filter: '(mailEnabled=TRUE)'
      value:
        - mailGroupMember:
            always_list: yes

    user_context:
      base: 'ou=People,dc=example,dc=com'
      filter: '(&(mailEnableIMAP=TRUE)(mailEnabled=TRUE))'

  tasks:
    - name: get members 
      set_fact:
        member: "{{ item }}"
      register: all_members
      with_ldap:
        - context: group_context

    - name: show members
      debug:
        var: all_members.results | map(attribute='ansible_facts') | list
```

output:
The bug is here, I expect two LISTS meaning the plugin should return a  LIST of LISTS when the `always_list` option is True
```
TASK [show members] **********************************************************************************************************************************************************
ok: [localhost] => {
    "all_members.results | map(attribute='ansible_facts') | list": [
        {
            "member": "cn=kon,ou=People,dc=example,dc=com"
        }, 
        {
            "member": "cn=tade,ou=People,dc=example,dc=com"
        }, 
        {
            "member": "cn=tade,ou=People,dc=example,dc=com"
        }
    ]
}
```


with more attributes:

playbook:
```yaml
---
- hosts: localhost
  vars:
    group_context:
      base: 'ou=Groups,dc=example,dc=com'
      filter: '(mailEnabled=TRUE)'
      value:
        - mailGroupMember:
            always_list: yes
        - mailEnabled:

    user_context:
      base: 'ou=People,dc=example,dc=com'
      filter: '(&(mailEnableIMAP=TRUE)(mailEnabled=TRUE))'

  tasks:
    - name: get members 
      set_fact:
        member: "{{ item }}"
      register: all_members
      with_ldap:
        - context: group_context

    - name: show members
      debug:
        var: all_members.results | map(attribute='ansible_facts') | list
```

output:
Now this works as expected, the mailGroupMember is a list of lists with the `always_list` option
```
TASK [show members] **********************************************************************************************************************************************************
ok: [localhost] => {
    "all_members.results | map(attribute='ansible_facts') | list": [
        {
            "member": {
                "dn": "cn=admin,ou=Groups,dc=example,dc=gr", 
                "mailEnabled": "TRUE", 
                "mailGroupMember": [
                    "cn=kon,ou=People,dc=example,dc=com", 
                    "cn=tade,ou=People,dc=example,dc=com"
                ], 
                "term": null
            }
        }, 
        {
            "member": {
                "dn": "cn=support,ou=Groups,dc=example,dc=com", 
                "mailEnabled": "TRUE", 
                "mailGroupMember": [
                    "cn=tade,ou=People,dc=example,dc=com"
                ], 
                "term": null
            }
        }
    ]
}
```
To make the above clear let's look the output with more attributes BUT WITHOUT the always_list option:
output:
```
TASK [show members] **********************************************************************************************************************************************************
ok: [localhost] => {
    "all_members.results | map(attribute='ansible_facts') | list": [
        {
            "member": {
                "dn": "cn=admin,ou=comoups,dc=example,dc=com", 
                "mailEnabled": "TRUE", 
                "mailGroupMember": [
                    "cn=kon,ou=People,dc=example,dc=com", 
                    "cn=tade,ou=People,dc=example,dc=com"
                ], 
                "term": null
            }
        }, 
        {
            "member": {
                "dn": "cn=support,ou=comoups,dc=example,dc=com", 
                "mailEnabled": "TRUE", 
                "mailGroupMember": "cn=tade,ou=People,dc=example,dc=com", 
                "term": null
            }
        }
    ]
}

```

so it's all in the title, `always_list` is not getting honored when a single attr is used, because of the source lines i've already commented so many times. if the code was not so messy the inconsistency would be obvious and i wouldn't have to spend time explaining an obvious bug, or even better i would have gone and created a PR to fix this but at this point this codebase is a mess and no tests are there to amend that.
