### ISSUE TITLE
Using delegate_to: breaks plugin?

### ISSUE THREAD

**Issue by cfiske** [quinot/ansible-plugin-lookup_ldap#29]
I have a rather odd issue. I have everything working great to query my LDAP server, retrieve a list of users and do what I need with it. However, if I add `delegate_to: locahost` to the task it causes the plugin to error with `SSLHandshake() failed: misc. bad certificate (-9825)'`.

So this works:
```
---
- hosts: fakehost
  connection: local
  gather_facts: no

  vars:
    my_users: []
    ldap_base: dc=domain,dc=com
    people_base: "ou=People,{{ ldap_base }}"
    ldap_lookup_config:
      url: 'ldaps://ldapserver.domain.com'
      base: "{{ people_base }}"
      binddn: "uid=myuser,ou=People,{{ ldap_base }}"
      bindpw: "mypassword"

    ldap_users:
      base: "{{ people_base }}"
      value: uid
      filter: '(!(loginShell=/bin/false))'

  tasks:
    - name: Fetch LDAP users
      set_fact:
        my_users: "{{ my_users }} + [ '{{ item }}' ]"
      with_ldap:
        - context: ldap_users
        - myldapgroup

    - name: Show users
      debug: msg="User {{ my_users }}"

  roles:
    - quinot.lookup_ldap
```
but this fails with the SSL cert error:
```
---
- hosts: fakehost
  gather_facts: no

  vars:
    my_users: []
    ldap_base: dc=domain,dc=com
    people_base: "ou=People,{{ ldap_base }}"
    ldap_lookup_config:
      url: 'ldaps://ldapserver.domain.com'
      base: "{{ people_base }}"
      binddn: "uid=myuser,ou=People,{{ ldap_base }}"
      bindpw: "mypassword"

    ldap_users:
      base: "{{ people_base }}"
      value: uid
      filter: '(!(loginShell=/bin/false))'

  tasks:
    - name: Fetch LDAP users
      delegate_to: localhost
      set_fact:
        my_users: "{{ my_users }} + [ '{{ item }}' ]"
      with_ldap:
        - context: ldap_users
        - myldapgroup

    - name: Show users
      debug: msg="User {{ my_users }}"

  roles:
    - quinot.lookup_ldap
```
I wondered if this might be a more general bug in Ansible with `delegate_to` but I don't believe so. If I replace `with_ldap` with a generic `with_items` then it works fine with `delegate_to`.
I inserted some debug logging and it's at the `lo.simple_bind_s()` stage that it fails when using `delegate_to: localhost`.
Also, while yes, it does work with `connection: local` instead, that does not solve for my use case. I need to be able to delegate facts to localhost.
Please let me know if I need to provide more details. This is with Ansible 2.7.5, Python 2.7.15 on MacOS High Sierra 10.13.5.

**Comment by evilhamsterman** [comment]
Lookup plugins run on the control machine, ie they already run on local host https://docs.ansible.com/ansible/latest/plugins/lookup.html

> Like all templating, these plugins are evaluated on the Ansible control machine, not on the target/remote.

**Comment by cfiske** [comment]
The plugin runs on the control machine, but the resulting facts are tied to the target host. So when I run this across multiple targets it has to repeat the identical lookup request for every host. I just want to query once and have that data accessible for every host in the run.

**Comment by evilhamsterman** [comment]
The point I'm trying to make is you are dealing with limitations of Ansible, not this plugin. Lookups don't support delegation https://github.com/ansible/ansible/issues/14940. 

However you can run lookups in the vars section rather than using set_fact I.E. something like this 
```YAML
---
- hosts: fakehost
  gather_facts: no

  vars:
    my_users: []
    ldap_base: dc=domain,dc=com
    people_base: "ou=People,{{ ldap_base }}"
    ldap_lookup_config:
      url: 'ldaps://ldapserver.domain.com'
      base: "{{ people_base }}"
      binddn: "uid=myuser,ou=People,{{ ldap_base }}"
      bindpw: "mypassword"

    ldap_users:
      base: "{{ people_base }}"
      value: uid
      filter: '(!(loginShell=/bin/false))'
    
    user:  "{{ lookup('ldap', 'myldapgroup', context='ldap_users') }}"
```
the with_<lookup> function is deprecated in newer Ansible versions and doesn't sound like what you want anyway. https://docs.ansible.com/ansible/latest/plugins/lookup.html

Honestly I don't think this plugin is going to get fixed, there are very few commits and none in over a year. Multiple people have tried to get pull requests to add Python 3 support but the dev won't pull them, and he still uses a weird methodology using the with_<lookup> format that isn't supported. There is a pull request for a proper LDAP lookup plugin for upstream Ansible that appears much better written and you could drop in and use instead. https://github.com/ansible/ansible/pull/52899
