### ISSUE TITLE
reconsider context naming convention

### ISSUE THREAD

**Issue by PhilEv** [quinot/ansible-plugin-lookup_ldap#3]
there are 2 points here:
1. having the '/' character as part of the context name is not so 'beautiful'

For examples as in  ldap_lookup_config/hosts or ldap_lookup_config/group_members_cn
this is because the '/' is used for file path on Linux or is very uncommon in variable names
1. do not assume the existence or the need to declared 'ldap_lookup_config' variable
   and have a simpler way to pass the needed information to the plugin
   the required info could be any yaml dictionary:
   the ldap url  and a context specifying the base  the value to get, filter etc...

this requires more thoughts but something along:

  vars:
    # Default context
    ldap_url: 'ldap://ldap.example.com'

```
# A context    # List all users, skip jpegPhoto
user_nophoto:
  base: ou=People,dc=example,dc=com
  value:
    - jpegPhoto: skip=True
  filter: (uid={{ term }})
```

  tasks:
    - name: Display one user, no photo
      debug: msg="User {{ item }}"
      with_ldap:
        - url: ldap_url
        - context: user_nophoto 
        - johndoe
