### ISSUE TITLE
trying to get the Max value of a search

### ISSUE THREAD

**Issue by roumano** [quinot/ansible-plugin-lookup_ldap#7]
Hi,

Maybe i missing something but i'm failling to get the maxium uidnumber with your module

in var, i have created this :  
```
    uidNumber:
      base: ou=People,dc=allclient,dc=com
      value: 
        - uidNumber: list=True
```

and i"m trying to get the biggest uidNumber of this request but all my test failed : 
```
    - name: Get all uidnumber
      debug: msg="{{ lookup('ldap' , context='uidNumber', value="uidNumber") }}"
```
will give 
```
    "msg": "5005,5567,5011,5106,5035,5052,5110,5002,7041
```
So can't use the  " | max " possiblity
i also have try  these 
``
    - name: Get uidMax
      set_fact: uid="{{ item }}"
      with_ldap:
        - context: uidNumber
      register: uid2
    - name: get only the last return uid
      debug: msg="{{ item }}"
      with_items:
        - "{{ uid }}"
    - name: found uidMax
      debug: msg="{{ item.results }}"
      with_items:
        - "{{ uid2 }}"
```
but all of them are failed.
