### ISSUE TITLE
the field 'args' has an invalid value ([]), and could not be converted to an dict

### ISSUE THREAD

**Issue by k0ste** [quinot/ansible-plugin-lookup_ldap#9]
Hello.

It seems there is a error when working with Unicode, when I try get value from nested key.

## Test data:

```yaml

---
ldap_lookup_config:
  url: 'ldap://127.0.0.1:389'
  base: 'dc=example,dc=com'
  binddn: 'cn=user,ou=people,dc=example,dc=com'
  bindpw: 'secret'
  scope: 'subtree'
  filter: '(objectClass=*)'

ldap_user_nophoto:
  base: 'ou=people,dc=example,dc=com'
  value:
  - jpegPhoto:
      skip: True
  filter: '(uid={{ term }})'
```

```yaml
---
- name: Direct lookup 1
  debug:
    msg: "{{ item }}"
  with_ldap:
  - context: 'ldap_user_nophoto'
  - value:
    - cn
  - "{{ lookup('env', 'USER') }}"

- name: Direct lookup 2
  debug:
    msg: "{{ item.cn }}"
  with_ldap:
  - context: 'ldap_user_nophoto'
  - value:
    - cn
    - mail
  - "{{ lookup('env', 'USER') }}"
```

## Expected results:
First and second task return identical msgs.

## Actual results:

```python
PLAY [Project DEPLOY] ********************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************
ok: [127.0.0.1]

TASK [project_deploy : Direct lookup 1] **************************************************************************************************************
ok: [127.0.0.1] => (item=Шалыгин Константин Николаевич) => {
    "item": "Шалыгин Константин Николаевич", 
    "msg": "Шалыгин Константин Николаевич"
}

TASK [project_deploy : Direct lookup 2] **************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value ([]), and could not be converted to an dict. Error was: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)\n\nThe error appears to have been in '/home/k0ste/sandbox/OpenTech/GIT/ansible-role-project_deploy/tasks/pre_requisite.yml': line 34, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Direct lookup 2\n  ^ here\n"}

PLAY RECAP *******************************************************************************************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=1   
```
